# # # NPCShop Config # # #
# <--> Developed by Silverwolfg11 <--> #

#Main inventory configuration. The one that pops up when an NPC is first clicked.
maininventory:
  buy-item:
    material: diamond
    placement: 0 #0-9 for the main inventory
    #Name and Lore optional
    name: "&aBuy"
    lore:
    - "&bOpen the buy inventory!"
  sell-item:
    material: diamond_ore
    placement: 1 #0-9 for the main inventory
    #Name and Lore optional
    name: "&bSell"
    lore:
      - "&bOpen the sell inventory!"


npcshops:
  #Put the NPC ID
  1:
    #Then the title of the inventory
    title: "&aMerchant's Shop"
    bank: false # This value represents whether to use Vault bank accounts for transactions. Optional, will default to false.
    items:
      #Put the material: amount buy price sell price
      stone: "25 200.0 100.0"


customitems:
  #The name of the custom item which will be used to parse items
  colorbook:
    #The material
    material: "enchanted_book"
    #The display name
    name: "&4C&6o&el&2o&1r &8Book"
    lore:
    - "Add a colored name"
    - "to your items!"
    #You can put enchantments
    #enchantments:
      #- "Unbreaking 3"
  nuketnt:
    #The material
    material: "tnt"
    #The display name
    name: "&cNuker"
    lore:
      - "Nuke yourself!"
    # Give the itemstack when a player buys this?
    giveonbuy: false
    # Take the itemstack when a player sell this?
    takeonsell: false
    # Custom Items can execute commands!
    buycommands:
      # The <player> is a placeholder for the player name!
      - "nuke <player>"
    sellcommands:
      - "say <player> sold his soul!"