name: NPCShop
main: me.Silverwolfg11.NPCShop.NPCShopPlugin
version: 1.0
api-version: 1.14
depend: [Vault, Citizens]
softdepend: [ProtocolLib]
description: A plugin that allows you to create shops for NPCs
commands:
  npcshop:
     description: Main command for npcshop!
     aliases: [ns]

permissions:
  npcshop.command:
    description: Permission to use npcshop command
    default: op
